import { Button, Navbar, NavbarBrand, NavbarCollapse, NavbarLink, NavbarToggle } from "flowbite-react";
import AnimatedLogo from "../global-components/AnimatedLogo";
import { AvatarDropdown } from "../global-components/AvatarDropdown";
import { getUserById, updateUserById, } from '@/src/db/queries'
import { auth } from '@/auth'
import Wrapper from './Container';
import { signOut } from '@/auth';
import type { Metadata } from "next";
import GlobalNavbar from "../global-components/GlobalNavbar";
import fs from 'fs';
import path from 'path';

export const metadata: Metadata = {
    title: "Your workspace",
    description: "Generated by create next app",
};

export default async function Page() {
    const session = await auth()
    const user = await getUserById(session?.user.id as string)

    // const tesseractTouch = fs.readFileSync(path.join(process.cwd(), 'node_modules/tesseract.js/src/worker-script/node/index.js'));
    // const tesseractTouchTwo = fs.readFileSync(path.join(process.cwd(), 'public/tesseract-core-simd.wasm'));
    // const tesseractTouchThree = fs.readFileSync(path.join(process.cwd(), 'node_modules/tesseract.js-core/tesseract-core.wasm.js'));

    return (
        <div className="divide-y divide-solid">
            <GlobalNavbar {...(user[0])} />
            <Wrapper user={await user} />
        </div>
    )
}
